name: Bug
description: Something broke
labels: ["type:bug"]
body:
  - type: input
    id: env
    attributes: { label: Environment, placeholder: "Pixel 7, Android 14" }
  - type: textarea
    id: repro
    attributes: { label: Steps to Reproduce }
  - type: textarea
    id: expected
    attributes: { label: Expected }
  - type: textarea
    id: actual
    attributes: { label: Actual }
  - type: textarea
    id: logs
    attributes: { label: Logs/Screenshots }
